# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/vic_edit_ui/ui_vic_edit.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from src.ui import resources_rc

class Ui_DialogVicEdit(object):
    def setupUi(self, DialogVicEdit):
        DialogVicEdit.setObjectName("DialogVicEdit")
        DialogVicEdit.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogVicEdit.resize(596, 245)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/edit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogVicEdit.setWindowIcon(icon)
        DialogVicEdit.setModal(True)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(DialogVicEdit)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(DialogVicEdit)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Category = QtWidgets.QLineEdit(DialogVicEdit)
        self.Category.setObjectName("Category")
        self.horizontalLayout.addWidget(self.Category)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(DialogVicEdit)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.VictimIdentified = QtWidgets.QLineEdit(DialogVicEdit)
        self.VictimIdentified.setObjectName("VictimIdentified")
        self.horizontalLayout_2.addWidget(self.VictimIdentified)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(DialogVicEdit)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.OffenderIdentified = QtWidgets.QLineEdit(DialogVicEdit)
        self.OffenderIdentified.setObjectName("OffenderIdentified")
        self.horizontalLayout_3.addWidget(self.OffenderIdentified)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(DialogVicEdit)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.Tags = QtWidgets.QLineEdit(DialogVicEdit)
        self.Tags.setObjectName("Tags")
        self.horizontalLayout_5.addWidget(self.Tags)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.IsDistributed = QtWidgets.QCheckBox(DialogVicEdit)
        self.IsDistributed.setObjectName("IsDistributed")
        self.horizontalLayout_4.addWidget(self.IsDistributed)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.IsPrecategorized = QtWidgets.QCheckBox(DialogVicEdit)
        self.IsPrecategorized.setObjectName("IsPrecategorized")
        self.horizontalLayout_6.addWidget(self.IsPrecategorized)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.IsSuspected = QtWidgets.QCheckBox(DialogVicEdit)
        self.IsSuspected.setObjectName("IsSuspected")
        self.horizontalLayout_7.addWidget(self.IsSuspected)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnAceptar = QtWidgets.QToolButton(DialogVicEdit)
        self.btnAceptar.setEnabled(True)
        self.btnAceptar.setMinimumSize(QtCore.QSize(50, 50))
        self.btnAceptar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconos/ok"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAceptar.setIcon(icon1)
        self.btnAceptar.setIconSize(QtCore.QSize(48, 48))
        self.btnAceptar.setObjectName("btnAceptar")
        self.verticalLayout_2.addWidget(self.btnAceptar, 0, QtCore.Qt.AlignTop)
        self.btnClose = QtWidgets.QToolButton(DialogVicEdit)
        self.btnClose.setMinimumSize(QtCore.QSize(50, 50))
        self.btnClose.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconos/cancel"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon2)
        self.btnClose.setIconSize(QtCore.QSize(48, 48))
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout_2.addWidget(self.btnClose, 0, QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)

        self.retranslateUi(DialogVicEdit)
        QtCore.QMetaObject.connectSlotsByName(DialogVicEdit)

    def retranslateUi(self, DialogVicEdit):
        _translate = QtCore.QCoreApplication.translate
        DialogVicEdit.setWindowTitle(_translate("DialogVicEdit", "Editar VIC Media Item..."))
        self.label.setText(_translate("DialogVicEdit", "Category:"))
        self.label_2.setText(_translate("DialogVicEdit", "VictimIdentified:"))
        self.label_3.setText(_translate("DialogVicEdit", "OffenderIdentified:"))
        self.label_5.setText(_translate("DialogVicEdit", "Tags:"))
        self.IsDistributed.setText(_translate("DialogVicEdit", "IsDistributed"))
        self.IsPrecategorized.setText(_translate("DialogVicEdit", "IsPrecategorized"))
        self.IsSuspected.setText(_translate("DialogVicEdit", "IsSuspected"))
        self.btnAceptar.setToolTip(_translate("DialogVicEdit", "Aceptar cambios."))
        self.btnAceptar.setStatusTip(_translate("DialogVicEdit", "Cerrar."))
        self.btnClose.setToolTip(_translate("DialogVicEdit", "Cancelar"))
        self.btnClose.setStatusTip(_translate("DialogVicEdit", "Cerrar."))

