# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/scann_ui/ui_nsfw_scann.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgNsfwScanner(object):
    def setupUi(self, dlgNsfwScanner):
        dlgNsfwScanner.setObjectName("dlgNsfwScanner")
        dlgNsfwScanner.setWindowModality(QtCore.Qt.NonModal)
        dlgNsfwScanner.resize(1074, 987)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlgNsfwScanner.sizePolicy().hasHeightForWidth())
        dlgNsfwScanner.setSizePolicy(sizePolicy)
        dlgNsfwScanner.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icon-wifi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgNsfwScanner.setWindowIcon(icon)
        dlgNsfwScanner.setToolTip("")
        dlgNsfwScanner.setLayoutDirection(QtCore.Qt.LeftToRight)
        dlgNsfwScanner.setSizeGripEnabled(False)
        dlgNsfwScanner.setModal(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(dlgNsfwScanner)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(dlgNsfwScanner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnScannFolder = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnScannFolder.sizePolicy().hasHeightForWidth())
        self.btnScannFolder.setSizePolicy(sizePolicy)
        self.btnScannFolder.setMinimumSize(QtCore.QSize(50, 50))
        self.btnScannFolder.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/icon-searchfolder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnScannFolder.setIcon(icon1)
        self.btnScannFolder.setIconSize(QtCore.QSize(48, 48))
        self.btnScannFolder.setObjectName("btnScannFolder")
        self.horizontalLayout.addWidget(self.btnScannFolder, 0, QtCore.Qt.AlignLeft)
        self.btnVIC = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnVIC.sizePolicy().hasHeightForWidth())
        self.btnVIC.setSizePolicy(sizePolicy)
        self.btnVIC.setMaximumSize(QtCore.QSize(52, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnVIC.setFont(font)
        self.btnVIC.setObjectName("btnVIC")
        self.horizontalLayout.addWidget(self.btnVIC)
        self.lblScannFolder = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblScannFolder.sizePolicy().hasHeightForWidth())
        self.lblScannFolder.setSizePolicy(sizePolicy)
        self.lblScannFolder.setMaximumSize(QtCore.QSize(16777215, 60))
        self.lblScannFolder.setWordWrap(False)
        self.lblScannFolder.setObjectName("lblScannFolder")
        self.horizontalLayout.addWidget(self.lblScannFolder)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSave = QtWidgets.QToolButton(self.layoutWidget1)
        self.btnSave.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy)
        self.btnSave.setMinimumSize(QtCore.QSize(50, 50))
        self.btnSave.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/icon-save-floppy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon2)
        self.btnSave.setIconSize(QtCore.QSize(48, 48))
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_2.addWidget(self.btnSave)
        self.lblSaveFolder = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSaveFolder.sizePolicy().hasHeightForWidth())
        self.lblSaveFolder.setSizePolicy(sizePolicy)
        self.lblSaveFolder.setMaximumSize(QtCore.QSize(16777215, 60))
        self.lblSaveFolder.setWordWrap(False)
        self.lblSaveFolder.setObjectName("lblSaveFolder")
        self.horizontalLayout_2.addWidget(self.lblSaveFolder)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chkShowImage = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkShowImage.setChecked(True)
        self.chkShowImage.setObjectName("chkShowImage")
        self.verticalLayout_3.addWidget(self.chkShowImage, 0, QtCore.Qt.AlignTop)
        self.chkGif_as_frame = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkGif_as_frame.setChecked(True)
        self.chkGif_as_frame.setObjectName("chkGif_as_frame")
        self.verticalLayout_3.addWidget(self.chkGif_as_frame, 0, QtCore.Qt.AlignTop)
        self.progressBarScore = QtWidgets.QProgressBar(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 141, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressBarScore.setPalette(palette)
        self.progressBarScore.setProperty("value", 15)
        self.progressBarScore.setObjectName("progressBarScore")
        self.verticalLayout_3.addWidget(self.progressBarScore, 0, QtCore.Qt.AlignTop)
        self.selScore = QtWidgets.QSlider(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 141, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.selScore.setPalette(palette)
        self.selScore.setMaximum(100)
        self.selScore.setProperty("value", 15)
        self.selScore.setOrientation(QtCore.Qt.Horizontal)
        self.selScore.setObjectName("selScore")
        self.verticalLayout_3.addWidget(self.selScore, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_3.addWidget(self.splitter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.video_viewer = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_viewer.sizePolicy().hasHeightForWidth())
        self.video_viewer.setSizePolicy(sizePolicy)
        self.video_viewer.setObjectName("video_viewer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.video_viewer)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.video = QtWidgets.QFrame(self.video_viewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video.sizePolicy().hasHeightForWidth())
        self.video.setSizePolicy(sizePolicy)
        self.video.setMinimumSize(QtCore.QSize(256, 256))
        self.video.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.video.setFrameShadow(QtWidgets.QFrame.Raised)
        self.video.setObjectName("video")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.video)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.video_progress = QtWidgets.QProgressBar(self.video)
        self.video_progress.setProperty("value", 0)
        self.video_progress.setAlignment(QtCore.Qt.AlignCenter)
        self.video_progress.setObjectName("video_progress")
        self.verticalLayout_5.addWidget(self.video_progress)
        self.video_frame = QtWidgets.QLabel(self.video)
        self.video_frame.setMinimumSize(QtCore.QSize(200, 200))
        self.video_frame.setMaximumSize(QtCore.QSize(220, 200))
        self.video_frame.setBaseSize(QtCore.QSize(220, 220))
        self.video_frame.setText("")
        self.video_frame.setScaledContents(True)
        self.video_frame.setObjectName("video_frame")
        self.verticalLayout_5.addWidget(self.video_frame, 0, QtCore.Qt.AlignTop)
        self.video_score = QtWidgets.QProgressBar(self.video)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.video_score.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.video_score.setFont(font)
        self.video_score.setProperty("value", 0)
        self.video_score.setAlignment(QtCore.Qt.AlignCenter)
        self.video_score.setObjectName("video_score")
        self.verticalLayout_5.addWidget(self.video_score, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addWidget(self.video)
        self.horizontalLayout_3.addWidget(self.video_viewer)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnStart = QtWidgets.QToolButton(self.groupBox)
        self.btnStart.setEnabled(False)
        self.btnStart.setMinimumSize(QtCore.QSize(50, 50))
        self.btnStart.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/icon-acsource.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStart.setIcon(icon3)
        self.btnStart.setIconSize(QtCore.QSize(48, 48))
        self.btnStart.setObjectName("btnStart")
        self.verticalLayout.addWidget(self.btnStart, 0, QtCore.Qt.AlignTop)
        self.btnPause = QtWidgets.QToolButton(self.groupBox)
        self.btnPause.setEnabled(False)
        self.btnPause.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/icon-handdrag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPause.setIcon(icon4)
        self.btnPause.setIconSize(QtCore.QSize(48, 48))
        self.btnPause.setCheckable(True)
        self.btnPause.setObjectName("btnPause")
        self.verticalLayout.addWidget(self.btnPause, 0, QtCore.Qt.AlignTop)
        self.btnAceptar = QtWidgets.QToolButton(self.groupBox)
        self.btnAceptar.setEnabled(False)
        self.btnAceptar.setMinimumSize(QtCore.QSize(50, 50))
        self.btnAceptar.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/icon-circleselect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAceptar.setIcon(icon5)
        self.btnAceptar.setIconSize(QtCore.QSize(48, 48))
        self.btnAceptar.setObjectName("btnAceptar")
        self.verticalLayout.addWidget(self.btnAceptar, 0, QtCore.Qt.AlignTop)
        self.btnClose = QtWidgets.QToolButton(self.groupBox)
        self.btnClose.setMinimumSize(QtCore.QSize(50, 50))
        self.btnClose.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/icon-circledelete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon6)
        self.btnClose.setIconSize(QtCore.QSize(48, 48))
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout.addWidget(self.btnClose, 0, QtCore.Qt.AlignTop)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.logImages = QtWidgets.QGroupBox(dlgNsfwScanner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logImages.sizePolicy().hasHeightForWidth())
        self.logImages.setSizePolicy(sizePolicy)
        self.logImages.setMinimumSize(QtCore.QSize(0, 0))
        self.logImages.setObjectName("logImages")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.logImages)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.logImagenes_hLayout = QtWidgets.QHBoxLayout()
        self.logImagenes_hLayout.setObjectName("logImagenes_hLayout")
        self.horizontalLayout_4.addLayout(self.logImagenes_hLayout)
        self.verticalLayout_2.addWidget(self.logImages)
        self.lblProgressBar = QtWidgets.QLabel(dlgNsfwScanner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProgressBar.sizePolicy().hasHeightForWidth())
        self.lblProgressBar.setSizePolicy(sizePolicy)
        self.lblProgressBar.setText("")
        self.lblProgressBar.setWordWrap(False)
        self.lblProgressBar.setObjectName("lblProgressBar")
        self.verticalLayout_2.addWidget(self.lblProgressBar)
        self.progressBar = QtWidgets.QProgressBar(dlgNsfwScanner)
        self.progressBar.setAutoFillBackground(True)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.txtLog = QtWidgets.QTextEdit(dlgNsfwScanner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtLog.sizePolicy().hasHeightForWidth())
        self.txtLog.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtLog.setPalette(palette)
        self.txtLog.setAutoFillBackground(False)
        self.txtLog.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.txtLog.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLog.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.txtLog.setReadOnly(True)
        self.txtLog.setAcceptRichText(False)
        self.txtLog.setObjectName("txtLog")
        self.verticalLayout_2.addWidget(self.txtLog)
        self.lblScannStatus = QtWidgets.QLabel(dlgNsfwScanner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblScannStatus.sizePolicy().hasHeightForWidth())
        self.lblScannStatus.setSizePolicy(sizePolicy)
        self.lblScannStatus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lblScannStatus.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setBold(False)
        font.setWeight(50)
        self.lblScannStatus.setFont(font)
        self.lblScannStatus.setAutoFillBackground(True)
        self.lblScannStatus.setText("")
        self.lblScannStatus.setTextFormat(QtCore.Qt.PlainText)
        self.lblScannStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblScannStatus.setWordWrap(False)
        self.lblScannStatus.setObjectName("lblScannStatus")
        self.verticalLayout_2.addWidget(self.lblScannStatus)
        self.lblScannFolder.setBuddy(self.btnScannFolder)
        self.lblSaveFolder.setBuddy(self.btnScannFolder)

        self.retranslateUi(dlgNsfwScanner)
        QtCore.QMetaObject.connectSlotsByName(dlgNsfwScanner)

    def retranslateUi(self, dlgNsfwScanner):
        _translate = QtCore.QCoreApplication.translate
        dlgNsfwScanner.setWindowTitle(_translate("dlgNsfwScanner", "Open Nsfw Scann v1.0 by MAX"))
        self.btnScannFolder.setToolTip(_translate("dlgNsfwScanner", "Directorio a Escanear."))
        self.btnScannFolder.setShortcut(_translate("dlgNsfwScanner", "Ctrl+S"))
        self.btnVIC.setToolTip(_translate("dlgNsfwScanner", "<html><head/><body><p>Escanear desde Reporte VIC 1.3.</p></body></html>"))
        self.btnVIC.setText(_translate("dlgNsfwScanner", "VIC"))
        self.lblScannFolder.setText(_translate("dlgNsfwScanner", "Seleccione el directorio a escanear!"))
        self.btnSave.setToolTip(_translate("dlgNsfwScanner", "Guardar Reporte."))
        self.lblSaveFolder.setText(_translate("dlgNsfwScanner", "Seleccione el Archivo para guaradar el Reporte!"))
        self.groupBox_2.setTitle(_translate("dlgNsfwScanner", "Configuraciones"))
        self.chkShowImage.setToolTip(_translate("dlgNsfwScanner", "<html><head/><body><p>Muestra una vista previa de las imagenes que esten por sobre la Probabilidad espesificada.</p></body></html>"))
        self.chkShowImage.setText(_translate("dlgNsfwScanner", "Mostrar Nsfw Imagenes"))
        self.chkGif_as_frame.setToolTip(_translate("dlgNsfwScanner", "<html><head/><body><p>Si esta activado escanea los GIF por frames como a los videos, de lo contrario los escanea como imagenes.</p></body></html>"))
        self.chkGif_as_frame.setText(_translate("dlgNsfwScanner", "Escanear GIF por frames"))
        self.selScore.setToolTip(_translate("dlgNsfwScanner", "<html><head/><body><p>Minima Probabilidad para considerar Nsfw Positivo.</p></body></html>"))
        self.video_viewer.setTitle(_translate("dlgNsfwScanner", "Escaneando Frames..."))
        self.btnStart.setStatusTip(_translate("dlgNsfwScanner", "Iniciar Escaneo."))
        self.btnPause.setToolTip(_translate("dlgNsfwScanner", "<html><head/><body><p>Pausar Proceso.</p><p><br/></p></body></html>"))
        self.btnAceptar.setStatusTip(_translate("dlgNsfwScanner", "Cerrar."))
        self.btnClose.setStatusTip(_translate("dlgNsfwScanner", "Cerrar."))
        self.logImages.setTitle(_translate("dlgNsfwScanner", "Ultimos Nsfw --->"))

