# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_nsfw_scann.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgNsfwScanner(object):
    def setupUi(self, dlgNsfwScanner):
        dlgNsfwScanner.setObjectName("dlgNsfwScanner")
        dlgNsfwScanner.setWindowModality(QtCore.Qt.ApplicationModal)
        dlgNsfwScanner.resize(1115, 571)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlgNsfwScanner.sizePolicy().hasHeightForWidth())
        dlgNsfwScanner.setSizePolicy(sizePolicy)
        dlgNsfwScanner.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icon-wifi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgNsfwScanner.setWindowIcon(icon)
        dlgNsfwScanner.setToolTip("")
        dlgNsfwScanner.setLayoutDirection(QtCore.Qt.LeftToRight)
        dlgNsfwScanner.setSizeGripEnabled(False)
        dlgNsfwScanner.setModal(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(dlgNsfwScanner)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(dlgNsfwScanner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnScannFolder = QtWidgets.QToolButton(self.layoutWidget)
        self.btnScannFolder.setMinimumSize(QtCore.QSize(50, 50))
        self.btnScannFolder.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/icon-searchfolder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnScannFolder.setIcon(icon1)
        self.btnScannFolder.setIconSize(QtCore.QSize(48, 48))
        self.btnScannFolder.setObjectName("btnScannFolder")
        self.horizontalLayout.addWidget(self.btnScannFolder, 0, QtCore.Qt.AlignLeft)
        self.lblScannFolder = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblScannFolder.sizePolicy().hasHeightForWidth())
        self.lblScannFolder.setSizePolicy(sizePolicy)
        self.lblScannFolder.setMaximumSize(QtCore.QSize(16777215, 60))
        self.lblScannFolder.setWordWrap(False)
        self.lblScannFolder.setObjectName("lblScannFolder")
        self.horizontalLayout.addWidget(self.lblScannFolder)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSaveFolder = QtWidgets.QToolButton(self.layoutWidget1)
        self.btnSaveFolder.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveFolder.sizePolicy().hasHeightForWidth())
        self.btnSaveFolder.setSizePolicy(sizePolicy)
        self.btnSaveFolder.setMinimumSize(QtCore.QSize(50, 50))
        self.btnSaveFolder.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/icon-createfolder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveFolder.setIcon(icon2)
        self.btnSaveFolder.setIconSize(QtCore.QSize(48, 48))
        self.btnSaveFolder.setObjectName("btnSaveFolder")
        self.horizontalLayout_2.addWidget(self.btnSaveFolder, 0, QtCore.Qt.AlignLeft)
        self.lblSaveFolder = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSaveFolder.sizePolicy().hasHeightForWidth())
        self.lblSaveFolder.setSizePolicy(sizePolicy)
        self.lblSaveFolder.setMaximumSize(QtCore.QSize(16777215, 60))
        self.lblSaveFolder.setWordWrap(False)
        self.lblSaveFolder.setObjectName("lblSaveFolder")
        self.horizontalLayout_2.addWidget(self.lblSaveFolder)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.progressBarScore = QtWidgets.QProgressBar(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 141, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.progressBarScore.setPalette(palette)
        self.progressBarScore.setProperty("value", 15)
        self.progressBarScore.setObjectName("progressBarScore")
        self.verticalLayout_3.addWidget(self.progressBarScore)
        self.selScore = QtWidgets.QSlider(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 141, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.selScore.setPalette(palette)
        self.selScore.setMaximum(100)
        self.selScore.setProperty("value", 15)
        self.selScore.setOrientation(QtCore.Qt.Horizontal)
        self.selScore.setObjectName("selScore")
        self.verticalLayout_3.addWidget(self.selScore)
        self.horizontalLayout_3.addWidget(self.splitter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnStart = QtWidgets.QToolButton(self.groupBox)
        self.btnStart.setEnabled(False)
        self.btnStart.setMinimumSize(QtCore.QSize(50, 50))
        self.btnStart.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/icon-acsource.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStart.setIcon(icon3)
        self.btnStart.setIconSize(QtCore.QSize(48, 48))
        self.btnStart.setObjectName("btnStart")
        self.verticalLayout.addWidget(self.btnStart)
        self.btnSave = QtWidgets.QToolButton(self.groupBox)
        self.btnSave.setEnabled(False)
        self.btnSave.setMinimumSize(QtCore.QSize(50, 50))
        self.btnSave.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/icon-save-floppy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon4)
        self.btnSave.setIconSize(QtCore.QSize(48, 48))
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout.addWidget(self.btnSave)
        self.btnClose = QtWidgets.QToolButton(self.groupBox)
        self.btnClose.setMinimumSize(QtCore.QSize(50, 50))
        self.btnClose.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/icon-circledelete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon5)
        self.btnClose.setIconSize(QtCore.QSize(48, 48))
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout.addWidget(self.btnClose)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox, 0, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(dlgNsfwScanner)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblProgressBar = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProgressBar.sizePolicy().hasHeightForWidth())
        self.lblProgressBar.setSizePolicy(sizePolicy)
        self.lblProgressBar.setText("")
        self.lblProgressBar.setWordWrap(False)
        self.lblProgressBar.setObjectName("lblProgressBar")
        self.verticalLayout_4.addWidget(self.lblProgressBar, 0, QtCore.Qt.AlignTop)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar, 0, QtCore.Qt.AlignTop)
        self.progressBar.raise_()
        self.lblProgressBar.raise_()
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.txtLog = QtWidgets.QTextEdit(dlgNsfwScanner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtLog.sizePolicy().hasHeightForWidth())
        self.txtLog.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtLog.setPalette(palette)
        self.txtLog.setAutoFillBackground(False)
        self.txtLog.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.txtLog.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtLog.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.txtLog.setReadOnly(True)
        self.txtLog.setAcceptRichText(False)
        self.txtLog.setObjectName("txtLog")
        self.verticalLayout_2.addWidget(self.txtLog)
        self.lblScannStatus = QtWidgets.QLabel(dlgNsfwScanner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblScannStatus.sizePolicy().hasHeightForWidth())
        self.lblScannStatus.setSizePolicy(sizePolicy)
        self.lblScannStatus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lblScannStatus.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setBold(False)
        font.setWeight(50)
        self.lblScannStatus.setFont(font)
        self.lblScannStatus.setAutoFillBackground(True)
        self.lblScannStatus.setText("")
        self.lblScannStatus.setTextFormat(QtCore.Qt.PlainText)
        self.lblScannStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblScannStatus.setWordWrap(False)
        self.lblScannStatus.setObjectName("lblScannStatus")
        self.verticalLayout_2.addWidget(self.lblScannStatus, 0, QtCore.Qt.AlignBottom)
        self.lblScannFolder.setBuddy(self.btnScannFolder)
        self.lblSaveFolder.setBuddy(self.btnScannFolder)

        self.retranslateUi(dlgNsfwScanner)
        QtCore.QMetaObject.connectSlotsByName(dlgNsfwScanner)

    def retranslateUi(self, dlgNsfwScanner):
        _translate = QtCore.QCoreApplication.translate
        dlgNsfwScanner.setWindowTitle(_translate("dlgNsfwScanner", "Open Nsfw Scann v1.0 by MAX"))
        self.btnScannFolder.setToolTip(_translate("dlgNsfwScanner", "Directorio a Escanear."))
        self.lblScannFolder.setText(_translate("dlgNsfwScanner", "Seleccione el directorio a escanear!"))
        self.btnSaveFolder.setStatusTip(_translate("dlgNsfwScanner", "Directorio para guardar reporte."))
        self.lblSaveFolder.setText(_translate("dlgNsfwScanner", "Seleccione el directorio para guaradar el Reporte!"))
        self.groupBox_2.setTitle(_translate("dlgNsfwScanner", "Filtro por Probabilidad "))
        self.btnStart.setStatusTip(_translate("dlgNsfwScanner", "Iniciar Escaneo."))
        self.btnSave.setToolTip(_translate("dlgNsfwScanner", "Guardar Reporte."))
        self.btnClose.setStatusTip(_translate("dlgNsfwScanner", "Cerrar."))

