# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1071, 734)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icon-searchfolder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnScannFolder = QtWidgets.QToolButton(self.groupBox)
        self.btnScannFolder.setText("")
        self.btnScannFolder.setIcon(icon)
        self.btnScannFolder.setIconSize(QtCore.QSize(48, 48))
        self.btnScannFolder.setObjectName("btnScannFolder")
        self.horizontalLayout.addWidget(self.btnScannFolder)
        self.btnOpenFolder = QtWidgets.QToolButton(self.groupBox)
        self.btnOpenFolder.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/icon-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpenFolder.setIcon(icon1)
        self.btnOpenFolder.setIconSize(QtCore.QSize(48, 48))
        self.btnOpenFolder.setObjectName("btnOpenFolder")
        self.horizontalLayout.addWidget(self.btnOpenFolder)
        self.btnCloseFolder = QtWidgets.QToolButton(self.groupBox)
        self.btnCloseFolder.setEnabled(False)
        self.btnCloseFolder.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/icon-deletefolderalt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCloseFolder.setIcon(icon2)
        self.btnCloseFolder.setIconSize(QtCore.QSize(48, 48))
        self.btnCloseFolder.setObjectName("btnCloseFolder")
        self.horizontalLayout.addWidget(self.btnCloseFolder)
        self.btnSave = QtWidgets.QToolButton(self.groupBox)
        self.btnSave.setEnabled(False)
        self.btnSave.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/icon-save-floppy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon3)
        self.btnSave.setIconSize(QtCore.QSize(48, 48))
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnList = QtWidgets.QToolButton(self.groupBox)
        self.btnList.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/icon-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnList.setIcon(icon4)
        self.btnList.setIconSize(QtCore.QSize(48, 48))
        self.btnList.setObjectName("btnList")
        self.horizontalLayout.addWidget(self.btnList)
        self.btnGrid = QtWidgets.QToolButton(self.groupBox)
        self.btnGrid.setEnabled(False)
        self.btnGrid.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/icon-th.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGrid.setIcon(icon5)
        self.btnGrid.setIconSize(QtCore.QSize(48, 48))
        self.btnGrid.setObjectName("btnGrid")
        self.horizontalLayout.addWidget(self.btnGrid)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnUnsSelect = QtWidgets.QToolButton(self.groupBox)
        self.btnUnsSelect.setEnabled(False)
        self.btnUnsSelect.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/icon-th-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUnsSelect.setIcon(icon6)
        self.btnUnsSelect.setIconSize(QtCore.QSize(48, 48))
        self.btnUnsSelect.setObjectName("btnUnsSelect")
        self.horizontalLayout.addWidget(self.btnUnsSelect)
        self.btnRemove = QtWidgets.QToolButton(self.groupBox)
        self.btnRemove.setEnabled(False)
        self.btnRemove.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/icon-trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemove.setIcon(icon7)
        self.btnRemove.setIconSize(QtCore.QSize(48, 48))
        self.btnRemove.setObjectName("btnRemove")
        self.horizontalLayout.addWidget(self.btnRemove)
        self.lblSelCount = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblSelCount.setFont(font)
        self.lblSelCount.setObjectName("lblSelCount")
        self.horizontalLayout.addWidget(self.lblSelCount)
        self.verticalLayout.addWidget(self.groupBox)
        self.lblOpenFolder = QtWidgets.QLabel(self.centralwidget)
        self.lblOpenFolder.setText("")
        self.lblOpenFolder.setWordWrap(True)
        self.lblOpenFolder.setObjectName("lblOpenFolder")
        self.verticalLayout.addWidget(self.lblOpenFolder)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.listReporte = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.listReporte.setFont(font)
        self.listReporte.setToolTip("")
        self.listReporte.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listReporte.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listReporte.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listReporte.setAlternatingRowColors(True)
        self.listReporte.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listReporte.setIconSize(QtCore.QSize(80, 80))
        self.listReporte.setFlow(QtWidgets.QListView.TopToBottom)
        self.listReporte.setProperty("isWrapping", True)
        self.listReporte.setGridSize(QtCore.QSize(200, 80))
        self.listReporte.setViewMode(QtWidgets.QListView.ListMode)
        self.listReporte.setModelColumn(0)
        self.listReporte.setUniformItemSizes(True)
        self.listReporte.setWordWrap(True)
        self.listReporte.setSelectionRectVisible(True)
        self.listReporte.setObjectName("listReporte")
        self.verticalLayout.addWidget(self.listReporte)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMouseTracking(False)
        self.statusbar.setToolTip("")
        self.statusbar.setToolTipDuration(0)
        self.statusbar.setStatusTip("")
        self.statusbar.setWhatsThis("")
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nsfw Report Explorer v1.0 by MAX"))
        self.btnScannFolder.setToolTip(_translate("MainWindow", "Escanear Directorio."))
        self.btnScannFolder.setAccessibleName(_translate("MainWindow", "Escanear Directorio."))
        self.btnOpenFolder.setToolTip(_translate("MainWindow", "Abrir Reporte."))
        self.btnCloseFolder.setToolTip(_translate("MainWindow", "Cerrar Reporte."))
        self.btnSave.setToolTip(_translate("MainWindow", "Guardar reporte."))
        self.btnList.setToolTip(_translate("MainWindow", "Ver Lista"))
        self.btnGrid.setToolTip(_translate("MainWindow", "Ver Mosaico"))
        self.btnUnsSelect.setToolTip(_translate("MainWindow", "Quitar Seleccion"))
        self.btnRemove.setToolTip(_translate("MainWindow", "Eliminar Seleccionados"))
        self.lblSelCount.setText(_translate("MainWindow", "0/0"))

